job("Run npm test and publish") {
  container(displayName = "Run publish script", image = "node:alpine") {
    shellScript {
      interpreter = "/bin/sh"
      content = """
                echo Install npm dependencies...
                echo Run build if it exists in package.json...
                echo Run tests...
                echo Run publishing...
            """
    }
  }
}
